### ISSUE TITLE
Don't require github username

### ISSUE THREAD

**Issue by stickystyle** [SamVerschueren/generator-aws-lambda#8]
While I see that you're using the username as a convenience function to set the name and email address in the package.json, I don't think it should be mandatory; like if someone doesn't enter it offer the option to enter the name and email manually. In my case my github account is completely unrelated to the company I'm doing work for, so I have to hop into the package.json and change it manually negating the convenience factor anyways.

I know it's a minor quibble, but it almost stopped me from using your generator as I immediately had to pause and jump into the source code to see why this module I just downloaded wants to know details about me and what is it going to do with them.

**Comment by SamVerschueren** [comment]
Good point. Will change that. Not sure when though but will keep you posted.

**Comment by SamVerschueren** [comment]
Released in `v1.1.0`
